workleap/wl-orbiter

packages/components/src/avatar/docs/Avatar.stories.mdx
packages/components/src/avatar/src/Avatar.css
packages/components/src/avatar/src/Avatar.tsx
packages/components/src/avatar/src/AvatarGroup.tsx
packages/components/src/avatar/tests/chromatic/Avatar.stories.tsx
packages/components/src/avatar/tests/chromatic/AvatarGroup.stories.tsx
packages/components/src/listbox/src/ListboxOption.tsx
packages/components/src/menu/src/MenuItem.tsx

Gave the Avatar component the new Brand

---

packages/components/src/switch/docs/Switch.stories.mdx
packages/components/src/switch/src/Switch.css
packages/components/src/switch/src/Switch.tsx
packages/components/src/switch/tests/chromatic/createTestSuite.jsx

Applied the new look to the switch component.

Feat: [OR-166] Switch rebrand

---

packages/components/src/badge/src/Badge.css

Added the new styling for the Badge component
Updated css and removed useless font-size on the dot. The not never has text.

Feat: [OR-130] Badge rebrand

---

packages/components/src/listbox/src/Listbox.css
packages/components/src/listbox/src/Listbox.tsx
packages/components/src/listbox/src/ListboxOption.tsx

Rebranded the Listbox component

Feat: [OR-153] Listbox rebrand

---

packages/components/src/disclosure/src/Disclosure.css

Issue:
Disclosure component needs to be branded with the Workleap theme.
- Replaced Orbit tokens with the Hopper ones.

Feature/OR 138 - Rebrand of Disclosure

---

packages/components/src/autocomplete/src/Autocomplete.css
packages/components/src/autocomplete/src/Autocomplete.tsx

Issue: OR-128
Autocomplete rebrand
Added new styles for no results and made the ellipsis for the no results work properly.

Feat: [OR-128] Autocomplete rebrand and ellipsis fix

---

packages/components/src/alert/src/Alert.css
packages/components/src/dialog/src/Dialog.css
packages/components/src/dialog/src/Dialog.tsx
packages/components/src/modal/docs/Modal.stories.mdx
packages/components/src/modal/src/Modal.css
packages/components/src/modal/tests/chromatic/Modal.stories.tsx
packages/components/src/overlay/src/Underlay.css

Issue:
Updated Modal to follow rebrand.
- Updated Modal, Alert and Dialog tokens.
- Adapted tests and samples to follow the intended font-size for default text color in Modals .

Feature/OR-158 - Rebrand of Modal / Dialog / Alert

---

packages/components/src/select/src/Select.css

Issue: OR-164
Adding new styling for Select

Feat: [OR-164] Select Rebrand

---

packages/components/src/accordion/src/Accordion.css

Issue:
Rebrand of Accordion Component
- Updated tokens to match Hopper tokens.

rebranded accordion

---

packages/components/src/checkbox/src/Checkbox.css

Feat(rebrand): Checkbox rebrand

---

packages/components/src/index.css

Issue:
Orbiter default font colour was set to an Orbit token
Swapped the font color for the right color.

update default font oclor

---

packages/components/src/link/src/Link.css

Issue:
- Link component needed a rebrand.
- Changed tokens for Hopper tokens

rebranded link component

---

packages/components/src/tile/src/Tile.css

Issue:
Tile component was not using Hopper Tokens.
Rebranded Tile Component to follow Hopper tokens. As there is no design for Tile this is loosely based on what it could be.

OR-173 - Rebranded Tile component

---

packages/components/src/radio/src/Radio.css

Feat(rebrand): rebrand radio button

---

.storybook/components/banner/Banner.css
.storybook/components/banner/Banner.tsx
.storybook/components/banner/index.ts
.storybook/components/index.ts
docs/getting-started/Installation.stories.mdx

Issue: OR-191
Added a banner on the installation page.
Created a new Banner component for storybook and used it inside the installation page.
It is a yellow block.

Feat: [OR-191] Added Banner on Installation page

---

packages/components/src/button/src/Button.css
packages/components/src/input-group/src/InputGroup.css
packages/components/src/styling/src/theming/hopper-theme.css

Issue: OR-195
Added missing styles in Button and Input Group
The Button inside an input group now has the same color border as the input.
The active style of a select will show above the input border.

Bug: [OR-195]

---

packages/components/src/accordion/src/Accordion.css
packages/components/src/box/docs/Box.stories.mdx

Issue: OR-193, OR-194
- Fixed the text that was in the Box component.
- Added the background color to the focus state of accordion. Also updated the focus ring for bordered accordion to go around the whole header.

Fix: [OR-193, OR-194] Box text and accordion focus

---

.changeset/nervous-rings-tan.md
packages/components/src/tile/src/Tile.css

Issue:
Fix for : https://github.com/gsoft-inc/wl-orbiter/issues/70
Modified the Tile css in order to match the intended design.

Redesign of Tile Component

---

.changeset/cyan-bobcats-mate.md
packages/components/src/toolbar/src/Toolbar.tsx

Issue:
- Is this testable with Jest or Chromatic screenshots?
- Does this need an update to the documentation?
If your answer is yes to any of these, please make sure to include it in your PR.

add toolbar slot to toolbar

---

.changeset/smart-terms-ring.md
packages/components/src/styling/src/styled-system/props-handler.ts

Issue:
- Is this testable with Jest or Chromatic screenshots?
- Does this need an update to the documentation?
If your answer is yes to any of these, please make sure to include it in your PR.

Fixed intellisence for border-radius, font-family and line-height in the styled system

---

docs/features/tokens/TokenTable.jsx
packages/components/package.json
yarn.lock

 update dependencies and add a null check

---

.changeset/thirty-flowers-yell.md
packages/components/src/input/src/Input.css
packages/components/src/input/src/useInput.ts
packages/components/src/input/src/useInputContent.tsx
packages/components/src/text-input/docs/TextInput.stories.mdx
packages/components/src/text-input/src/PasswordInput.tsx
packages/components/src/text-input/src/SearchInput.tsx
packages/components/src/text-input/src/TextInput.tsx
packages/components/src/text-input/tests/chromatic/PasswordInput.stories.tsx
packages/components/src/text-input/tests/chromatic/SearchInput.stories.tsx
packages/components/src/text-input/tests/chromatic/TextInput.stories.tsx

Issue:
Input were not supporting the small size that Hopper supports.
Added support and tests for small size variations for TextInput / SearchInput and PasswordInput

added small size for text input / search input and passwordinput

---

.changeset/young-colts-wave.md
packages/components/src/avatar/src/Avatar.tsx

Avatar text color was not right, this fixes the issue.

fixed an issue where the initial color in avatar was not right

---

.changeset/proud-needles-dream.md

changeset for pr-112

---

.changeset/pink-llamas-buy.md
packages/components/src/button/src/Button.css
packages/components/src/button/src/TextButton.css
packages/components/src/button/tests/chromatic/createButtonTestSuite.jsx

Changes:
Adjusted styling to center icons and counter within fluid button components.

Centered icons and counter in fluid button

---

.changeset/thirty-guests-love.md
packages/components/package.json
packages/components/src/button/src/Button.css
packages/components/src/checkbox/src/Checkbox.css
packages/components/src/date-input/src/DateRangeInput.css
packages/components/src/index.css
packages/components/src/input/src/Input.css
packages/components/src/listbox/src/Listbox.css
packages/components/src/menu/src/Menu.css
packages/components/src/radio/src/Radio.css
packages/components/src/select/src/Select.css
packages/components/src/switch/src/Switch.css
packages/components/src/tile/src/Tile.css
packages/components/src/tooltip/src/Tooltip.css
packages/css/package.json
yarn.lock

Updated Orbiter to latest Hopper tokens and icon versions.

updated to latest hopper tokens and icons

---

.changeset/spotty-plums-travel.md
packages/css/package.json
yarn.lock

Updated Orbiter to latest Hopper tokens

updated to latest hopper token deps

---

.changeset/yellow-beers-glow.md
packages/components/src/button/src/Button.css

Hopper changed the ghost button text and icon color, this PR apply these changes.

updated tertiary button color

---

.changeset/sharp-feet-kneel.md
packages/components/src/badge/src/Badge.css
packages/components/src/badge/src/Badge.tsx
packages/components/src/lozenge/src/Lozenge.tsx
packages/components/src/tag/src/Tag.tsx

Issue:
Badge, Lozenge and Tag font size were not matching Hopper design.
Changed the mapping of text size.

Adjusted the Badge / Lozenge and Tag font size to match Hopper

---

packages/components/src/field/docs/Field.mdx
packages/components/src/field/docs/Field.stories.tsx

Following a question we receive, i improved the doc regarding the validation state in the field component

Updated the doc to better showcase the validationState prop  in the Field component

---

.changeset/short-planes-exercise.md
packages/components/src/checkbox/src/Checkbox.css

Issue: https://workleap.atlassian.net/browse/DS-531
Fix checkbox size sm unchecked

Fix checkbox size sm unchecked

---

.github/composite-actions/setup/action.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml
package.json

Issue:
- Is this testable with Jest or Chromatic screenshots?
- Does this need an update to the documentation?
If your answer is yes to any of these, please make sure to include it in your PR.

Update to pnpm 10 and update CI files

---

.github/PULL_REQUEST_TEMPLATE.md
.storybook/components/github-link/getGithubUrl.ts
.storybook/manager-head.html
.storybook/styles/themes.ts
CONTRIBUTING.md
docs/getting-started/Installation.mdx
package.json
packages/components/CHANGELOG.md
packages/components/README.md
packages/components/package.json
packages/components/src/avatar/docs/Avatar.stories.tsx
packages/components/src/core.css

TOPS-800: Replacing gsoft-inc/wl-reusable-workflows by workleap/wl-reusable-workflows
--
Not sure why this PR has been created? Reach TechOps in our public slack channel: #techops-and-friends
Some context on the why of this PR can be found here: https://workleap.slack.com/archives/C02E9KPRQ7P/p1737385211295479

hotfix/TOPS-800: Renaming gsoft-inc organization to workleap in github.
